### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by beradrian** [werk85/typed-cordova-plugin-purchase#2]
Is there somewhere a working example for this?

**Comment by beradrian** [comment]
I tried to add `node_modules/typed-cordova-plugin-purchase` to `typeRoots`, but I still get `Cannot find name 'store'`. I also added `typed-cordova-plugin-purchase` to `types` Do I have to import something?

**Comment by mlegenhausen** [comment]
```json
"include": [
    "node_modules/typed-cordova-plugin-purchase/index.d.ts",
    "src/**/*"
  ],
```

Try to add it to the `include` part of your `tsconfig.json` this works for me.

**Comment by beradrian** [comment]
I added it. Still the same error.

I'm using angular-cli 1.0.1

**Comment by mlegenhausen** [comment]
Never tested it with angular-cli before.

**Comment by beradrian** [comment]
Do you have a minimal working example?

**Comment by mlegenhausen** [comment]
No sorry I only use it in a bigger project.

Maybe you need to experiment with the `types` attribute cause this limits the allowed types used in your project.

**Comment by beradrian** [comment]
I added `"typed-cordova-plugin-purchase"` to `types`.

**Comment by beradrian** [comment]
It finally worked, all I had to do was 

    import 'typed-cordova-plugin-purchase';
